### ISSUE TITLE
Can not 'Set to Draft' generated folio in hotel management

### ISSUE THREAD

**Issue by Vishal-Mak** [JayVora-SerpentCS/hotelmgmt_v8#102]
Hello,
I have installed hotel module, Generate new folio from Menu: 
Hotel Management --> Folio -->Generate Folio and confirm it.
When try to 'Set to Draft' it gives following traceback : 

Traceback (most recent call last):
  File "/home/serpentcs/workspace_nesm/10/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/serpentcs/workspace_nesm/10/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/serpentcs/workspace_nesm/10/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/serpentcs/workspace_nesm/10/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/serpentcs/workspace_nesm/10/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/serpentcs/workspace_nesm/10/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/serpentcs/workspace_nesm/10/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/serpentcs/workspace_nesm/10/odoo/addons/web/controllers/main.py", line 886, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/serpentcs/workspace_nesm/10/odoo/addons/web/controllers/main.py", line 874, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/serpentcs/workspace_nesm/10/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/serpentcs/workspace_nesm/10/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/serpentcs/workspace_nesm/OdooHotelManagementSystem/hotel/models/hotel.py", line 707, in action_cancel_draft
    self.write({'state': 'draft', 'invoice_ids': [], 'shipped': 0})
  File "/home/serpentcs/workspace_nesm/OdooHotelManagementSystem/hotel/models/hotel.py", line 485, in write
    reservation_line_obj = self.env['hotel.room.reservation.line']
  File "/home/serpentcs/workspace_nesm/10/odoo/odoo/api.py", line 752, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/home/serpentcs/workspace_nesm/10/odoo/odoo/modules/registry.py", line 170, in __getitem__
    return self.models[model_name]
KeyError: 'hotel.room.reservation.line'

**Comment by camilozuluaga** [comment]
Hello, good day, may I ask you a question When you create a reservation from a quick reservation that shows a table and you select the room, the room will be loaded in the form. thank you very much.

**Comment by JayVora-SerpentCS** [comment]
Interesting that you get the error. We will check and revert back.

**Comment by KrishnaPrajapati-SerpentCS** [comment]
Hello,
I have checked and followed your mentioned steps but there is no such error.
Thanks

**Comment by camilozuluaga** [comment]
@krishnaprajapati16894 
It is up to you if you charge the room, when making the reservation fast. Thank you very much and sorry to bother you.

**Comment by JayVora-SerpentCS** [comment]
@Vishal-Mak , the error meant to say that your model pool does not have the model. This is possible when you have the addons path misconfigured.
Would you please check and help us know the pool?
Thanks.

**Comment by Vishal-Mak** [comment]
@JayVora-SerpentCS 
I have double check addons path  and it has been configured correct.
Model 'hotel.room.reservation.line' define in 'hotel_reservation' module and this module is not installed in database. What if I installed only hotel module ? 
Should 'hotel' module have dependency of 'hotel_reservation' module ?

**Comment by JayVora-SerpentCS** [comment]
@krishnaprajapati16894 please check that hotel_reservation models should not be used inside hotel module.

**Comment by KrishnaPrajapati-SerpentCS** [comment]
@JayVora-SerpentCS
Yes, I have check that hotel_reservation models should not be used inside hotel module.

@Vishal-Mak When you install hotel_reservation module then automatic install hotel module and hotel_reservation module is installed in the database.

**Comment by JayVora-SerpentCS** [comment]
This should be fixed by the latest source, do tell us if not.
