### ISSUE TITLE
board for hotel front desk

### ISSUE THREAD

**Issue by bleuubuntu** [JayVora-SerpentCS/hotelmgmt_v8#141]
I get this error 
Traceback (most recent call last):
  File "/odoo/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo/odoo/addons/base/module/module.py", line 411, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo/odoo/modules/loading.py", line 159, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/odoo/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1229, in _update
    record = record.create(values)
  File "/odoo/custom/addons/hotel_restaurant/models/hotel_restaurant.py", line 715, in create
    return super(HotelReservationOrder, self).create(vals)
  File "/odoo/odoo/odoo/models.py", line 3823, in create
    record = self.browse(self._create(old_vals))
  File "/odoo/odoo/odoo/models.py", line 3918, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/odoo/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ParseError: "date/time field value out of range: "04/23/2013 16:39:00"
LINE 1: ...VALUES(nextval('hotel_reservation_order_id_seq'), '04/23/201...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.
" while parsing /odoo/custom/addons/hotel_restaurant/views/hotel_restaurant_data.xml:217, near
<record id="hotel_reservation_order_1" model="hotel.reservation.order">
        <field name="table_no" eval="[(6,0,[ref('hotel_restaurant.hotel_restaurant_tables_table2'),ref('hotel_restaurant.hotel_restaurant_tables_table3')])]"/>
        <field eval="&quot;04/23/2013 16:39:00&quot;" name="date1"/>
        <field eval="&quot;ORR/00002&quot;" name="order_number"/>
        <field ref="hotel_restaurant_reservation_1" name="reservationno"/>
    </record>

**Comment by JayVora-SerpentCS** [comment]
This is due to bad demo data. @KrishnaPrajapati-SerpentCS please check.

**Comment by KrishnaPrajapati-SerpentCS** [comment]
@bleuubuntu I have checked all modules of hotel management and tried to generate the same error but I have not been able to capture it.
Please if you could let us know more about which modules exactly you have installed/updated it would me understand the issue better.

**Comment by bleuubuntu** [comment]
Hello,
First think you for you great work, and like you send me the first message,
that was due to demo data, after installing module with no demo, I was able
to test all the module with no problem, if you want I can try to recreat a
database with demo and send it to you.
think you again

2018-02-07 12:15 GMT+01:00 Krishna Prajapati <notifications@github.com>:

**Comment by KrishnaPrajapati-SerpentCS** [comment]
Hello @bleuubuntu,
I have checked all hotel management modules with no demo and I have not been able to capture any error.

**Comment by bleuubuntu** [comment]
Yes when no demo, no problem
