### ISSUE TITLE
POS Folio

### ISSUE THREAD

**Issue by jvpacoin** [JayVora-SerpentCS/hotelmgmt_v8#149]
Hi Ive install the hotel management system on odoo 10 and everything seems to work fine especially in hotel pos folio, i can send bills to hotel guest folio but once i close the POS i cant validate and post entries. it will give me this error: 

Odoo
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\odoo10\server\odoo\http.py", line 642, in _handle_exception
  File "C:\Program Files (x86)\odoo10\server\odoo\http.py", line 684, in dispatch
  File "C:\Program Files (x86)\odoo10\server\odoo\http.py", line 334, in _call_function
  File "C:\Program Files (x86)\odoo10\server\odoo\service\model.py", line 101, in wrapper
  File "C:\Program Files (x86)\odoo10\server\odoo\http.py", line 327, in checked_call
  File "C:\Program Files (x86)\odoo10\server\odoo\http.py", line 942, in __call__
  File "C:\Program Files (x86)\odoo10\server\odoo\http.py", line 507, in response_wrap
  File "C:\Program Files (x86)\odoo10\server\odoo\addons\web\controllers\main.py", line 896, in call_button
  File "C:\Program Files (x86)\odoo10\server\odoo\addons\web\controllers\main.py", line 884, in _call_kw
  File "C:\Program Files (x86)\odoo10\server\odoo\api.py", line 689, in call_kw
  File "C:\Program Files (x86)\odoo10\server\odoo\api.py", line 680, in call_kw_multi
  File "C:\Program Files (x86)\odoo10\server\odoo\addons\pos_fixes\models\pos_session.py", line 18, in action_pos_session_closing_control
  File "C:\Program Files (x86)\odoo10\server\odoo\addons\point_of_sale\models\pos_session.py", line 250, in action_pos_session_closing_control
  File "C:\Program Files (x86)\odoo10\server\odoo\addons\point_of_sale\models\pos_session.py", line 266, in action_pos_session_close
  File "C:\Program Files (x86)\odoo10\server\odoo\addons\pos_receipt\models\pos_receipt.py", line 411, in _confirm_orders
AttributeError: 'pos.order' object has no attribute '_create_accnt_move'

**Comment by jeffrepo** [comment]
¿how can i activate POS Folio button ?
