### ISSUE TITLE
No matching record found for external id 'model_room_rent' in field 'Object'

### ISSUE THREAD

**Issue by Vassy** [JayVora-SerpentCS/hotelmgmt_v8#2]
Hi Jay Vora! Thanks for publishing this module.  When i install hotel module, Odoo 8 get the error:

Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 476, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 495, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 311, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 308, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 685, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 360, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 944, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 932, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 233, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 233, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/module/module.py", line 497, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 357, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 182, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 978, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/opt/odoo/odoo/openerp/tools/convert.py", line 1046, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading hotel failed: file hotel/security/ir.model.access.csv could not be processed:
 Line 4 : No matching record found for external id 'model_room_rent' in field 'Object'

How to resolve this?
Regards,
Vassy

**Comment by Padmahas** [comment]
Hey @JayVora-SerpentCS, it rises exception but how to fix this?

**Comment by JayVora-SerpentCS** [comment]
@Padmahas Did you take the latest source?
