### ISSUE TITLE
Error when installing the module. Any help

### ISSUE THREAD

**Issue by zero-code** [JayVora-SerpentCS/hotelmgmt_v8#30]
Odoo Server Error

Traceback (most recent call last):
  File "/grandstar/grandstar-server/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/grandstar/grandstar-server/openerp/http.py", line 636, in dispatch
    result = self._call_function(*_self.params)
  File "/grandstar/grandstar-server/openerp/http.py", line 315, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/grandstar/grandstar-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/grandstar/grandstar-server/openerp/http.py", line 308, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/grandstar/grandstar-server/openerp/http.py", line 887, in __call__
    return self.method(_args, *_kw)
  File "/grandstar/grandstar-server/openerp/http.py", line 465, in response_wrap
    response = f(_args, *_kw)
  File "/grandstar/grandstar-server/addons/web/controllers/main.py", line 979, in call_button
    action = self._call_kw(model, method, args, {})
  File "/grandstar/grandstar-server/addons/web/controllers/main.py", line 967, in _call_kw
    return checked_call(request.db, _args, *_kwargs)
  File "/grandstar/grandstar-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/grandstar/grandstar-server/addons/web/controllers/main.py", line 966, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/grandstar/grandstar-server/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/grandstar/grandstar-server/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/grandstar/grandstar-server/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/grandstar/grandstar-server/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/grandstar/grandstar-server/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/grandstar/grandstar-server/openerp/modules/loading.py", line 337, in load_modules
    loaded_modules, update_module)
  File "/grandstar/grandstar-server/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/grandstar/grandstar-server/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/grandstar/grandstar-server/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/grandstar/grandstar-server/openerp/tools/convert.py", line 852, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/grandstar/grandstar-server/openerp/tools/convert.py", line 939, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/grandstar/grandstar-server/openerp/tools/convert.py", line 802, in parse
    self.parse(rec, mode)
  File "/grandstar/grandstar-server/openerp/tools/convert.py", line 805, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/grandstar/grandstar-server/openerp/tools/convert.py", line 778, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/grandstar/grandstar-server/openerp/tools/convert.py", line 709, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/grandstar/grandstar-server/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/grandstar/grandstar-server/openerp/addons/base/ir/ir_model.py", line 1105, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/grandstar/grandstar-server/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/grandstar/grandstar-server/openerp/addons/base/ir/ir_ui_view.py", line 351, in create
    context=context)
  File "/grandstar/grandstar-server/openerp/api.py", line 232, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/grandstar/grandstar-server/openerp/api.py", line 327, in old_api
    result = method(recs, _args, *_kwargs)
  File "/grandstar/grandstar-server/openerp/models.py", line 4125, in create
    record = self.browse(self._create(old_vals))
  File "/grandstar/grandstar-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/grandstar/grandstar-server/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/grandstar/grandstar-server/openerp/models.py", line 4316, in _create
    recs._validate_fields(vals)
  File "/grandstar/grandstar-server/openerp/api.py", line 230, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/grandstar/grandstar-server/openerp/models.py", line 1267, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
Element '<xpath expr="//div[@name='company_address']">' cannot be located in parent view

Error context:
View `report.external_layout_header`
[view_id: 176, xml_id: report.external_layout_header, model: n/a, parent_id: n/a]
None" while parsing None:9, near
<data inherit_id="report.external_layout_header" primary="True">
            <xpath expr="//div[@name='company_address']" position="after">
                <div class="col-xs-4 pull-right" name="right_box">
                    <img t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('Code128', o.name, 600, 100)" style="width:300px;height:50px;"/>
                </div>
            </xpath>
        <xpath position="attributes" expr="."><attribute name="t-name">stock.external_layout_header_barcode_right</attribute></xpath></data>

**Comment by JayVora-SerpentCS** [comment]
trying  v8 or v9?

**Comment by zero-code** [comment]
V9

**Comment by SerpentCS** [comment]
Hello,
We have made required changes and upgraded the code.
Please pull the latest code and install the modules with new database.

**Comment by zero-code** [comment]
I did and it solved the problem but this time round, I'm getting timezone
error

**Comment by SerpentCS** [comment]
Hello,

We have upgraded the code to resolve that issue.
Please pull the latest code and try.

Thank you for using our repository.
