### ISSUE TITLE
Installation of hotel fails:  '<xpath expr="//div[@name='company_address']">' cannot be located in parent view

### ISSUE THREAD

**Issue by robertrottermann** [JayVora-SerpentCS/hotelmgmt_v8#51]
I tried to install the hotel module in a english/german odoo environment.
It fails with the following error.

thanks
robert@redcor.ch

Odoo Server Error

Traceback (most recent call last):
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/http.py", line 680, in dispatch
    result = self._call_function(*_self.params)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/http.py", line 959, in __call__
    return self.method(_args, *_kw)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/http.py", line 509, in response_wrap
    response = f(_args, *_kw)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/tools/convert.py", line 777, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/addons/base/ir/ir_model.py", line 1120, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/addons/base/ir/ir_ui_view.py", line 351, in create
    context=context)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/models.py", line 4131, in create
    record = self.browse(self._create(old_vals))
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/models.py", line 4322, in _create
    recs._validate_fields(vals)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/robert/projects/breitschtraeff9/breitschtraeff9/parts/odoo/openerp/models.py", line 1270, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
Element '<xpath expr="//div[@name='company_address']">' cannot be located in parent view

Error context:
View `report.external_layout_header`
[view_id: 176, xml_id: report.external_layout_header, model: n/a, parent_id: n/a]
None" while parsing None:9, near
<data inherit_id="report.external_layout_header" primary="True">
            <xpath expr="//div[@name='company_address']" position="after">
                <div class="col-xs-4 pull-right" name="right_box">
                    <img t-att-src="'/report/barcode/?type=%s&amp;value=%s&amp;width=%s&amp;height=%s' % ('Code128', o.name, 600, 100)" style="width:300px;height:50px;"/>
                </div>
            </xpath>
        <xpath position="attributes" expr="."><attribute name="t-name">stock.external_layout_header_barcode_right</attribute></xpath></data>

**Comment by robertrottermann** [comment]
ah, I try to install the v9 branch
robert

**Comment by JayVora-SerpentCS** [comment]
Will check asap

**Comment by JayVora-SerpentCS** [comment]
@robertrottermann We've tried a clean install and it works pretty smooth on v8 and v9 both.
The possible concerns at your end could be, the latest source unavailability and other custom module altering the report module.
Kindly let us know more.
Thanks.
