### ISSUE TITLE
hotel_housekeeping: error on install (Odoo 8 build 14/3/2015 linux 64)

### ISSUE THREAD

**Issue by akram1** [JayVora-SerpentCS/hotelmgmt_v8#7]
Odoo Server Error
Traceback (most recent call last):
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/media/akram/Data/projects/servers/Odoo8/source/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/media/akram/Data/projects/servers/Odoo8/source/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/modules/loading.py", line 179, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/tools/convert.py", line 755, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/tools/convert.py", line 832, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/tools/convert.py", line 843, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/addons/base/ir/ir_model.py", line 932, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/tools/cache.py", line 71, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/media/akram/Data/projects/servers/Odoo8/source/openerp/addons/base/ir/ir_model.py", line 922, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: hotel_housekeeping.null" while parsing /media/akram/Data/projects/servers/testaddons/hotel_housekeeping/hotel_housekeeping_data.xml:5, near
<record id="hotel_housekeeping_activity_type_0" model="hotel.housekeeping.activity.type">
			<field name="parent_id" ref="null"/>
			<field name="name">All Activities</field>
		</record>

**Comment by Danisan** [comment]
I'v got the same.

**Comment by akram1** [comment]
I fixed it by removing ref="null" from line 6 in In hotel_housekeeping/hotel_housekeeping_data.xml
Not sure this has no effect on functionality of the module.
I also noticed the hotel module still uses the old api and style of programming.

**Comment by JayVora-SerpentCS** [comment]
Please try out with the latest code.
Thanks,
