### ISSUE TITLE
When creating amenities or rooms.. similar error..

### ISSUE THREAD

**Issue by Danisan** [JayVora-SerpentCS/hotelmgmt_v8#8]
Reproduced partially
[......]
  File "/opt/odoo/openerp/models.py", line 3286, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/opt/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: invalid reference to FROM-clause entry for table "product_product"
LINE 2: ...product_id" = "hotel_room__product_id"."id") AND ("product_p...
                                                             ^
HINT:  Perhaps you meant to reference the table alias "hotel_room__product_id".

**Comment by Danisan** [comment]
Similar for amenities...
[...] 
File "/opt/odoo/openerp/models.py", line 3286, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/opt/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: invalid reference to FROM-clause entry for table "product_product"
LINE 2: ... "hotel_room_amenities__room_categ_id"."id") AND ("product_p...
                                                             ^
HINT:  Perhaps you meant to reference the table alias "hotel_room_amenities__room_categ_id".

**Comment by Danisan** [comment]
@JayVora-SerpentCS, I saw this forum post:
https://www.odoo.com/forum/help-1/question/openerp-7-hotel-module-related-error-53947

and the error seems related to this same issue, but I saw in the code that kanban view is commented. As this is not a python error is being very difficult for me to debug. Could you please give a little hint to me in order to investigate it? perhaps I could contribute the solution..

Thanks a lot.

**Comment by Dayssam** [comment]
same problem

2015-07-12 16:39:20,962 6783 ERROR Clinic openerp.sql_db: Programming error: invalid reference to FROM-clause entry for table "product_product"
LINE 2: ...product_id" = "hotel_room__product_id"."id") AND ("product_p...
                                                             ^
HINT:  Perhaps you meant to reference the table alias "hotel_room__product_id".
, in query  SELECT product_product__product_tmpl_id."categ_id","hotel_room"."status","hotel_room"."capacity",product_product__product_tmpl_id."list_price","hotel_room"."id" FROM "hotel_room","product_product" as "hotel_room__product_id","product_template" as "product_product__product_tmpl_id"
                        WHERE "hotel_room".id IN %s AND ("hotel_room"."product_id" = "hotel_room__product_id"."id") AND ("product_product"."product_tmpl_id" = "product_product__product_tmpl_id"."id")  ORDER BY "hotel_room"."id"  
                    
2015-07-12 16:39:20,962 6783 ERROR Clinic openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/inovativ/workspace/Odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/inovativ/workspace/Odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/home/inovativ/workspace/Odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/inovativ/workspace/Odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/inovativ/workspace/Odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/inovativ/workspace/Odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/home/inovativ/workspace/Odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/home/inovativ/workspace/OdooRH/addons/web/controllers/main.py", line 875, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/inovativ/workspace/OdooRH/addons/web/controllers/main.py", line 896, in do_search_read
    request.context)
  File "/home/inovativ/workspace/Odoo/openerp/http.py", line 900, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/home/inovativ/workspace/Odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/inovativ/workspace/Odoo/openerp/models.py", line 5130, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/home/inovativ/workspace/Odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/inovativ/workspace/Odoo/openerp/models.py", line 3128, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/inovativ/workspace/Odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/inovativ/workspace/Odoo/openerp/models.py", line 3163, in read
    self._read_from_database(stored, inherited)
  File "/home/inovativ/workspace/Odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/inovativ/workspace/Odoo/openerp/models.py", line 3286, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/home/inovativ/workspace/Odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/inovativ/workspace/Odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: invalid reference to FROM-clause entry for table "product_product"
LINE 2: ...product_id" = "hotel_room__product_id"."id") AND ("product_p...
                                                             ^
HINT:  Perhaps you meant to reference the table alias "hotel_room__product_id".

**Comment by JayVora-SerpentCS** [comment]
@Danisan Its resolved in Official Odoo. Please check https://github.com/odoo/odoo/issues/5761.
